### ISSUE TITLE
ImportError: cannot import name 'ShardingStrategy' from 'torch.distributed.fsdp.fully_sharded_data_parallel

### ISSUE THREAD

**Issue by h2bit** [huggingface/accelerate#436]
### System Info

```Shell
- `Accelerate` version: 0.9.0
- Platform: Linux-5.15.0-35-generic-x86_64-with-glibc2.17
- Python version: 3.8.13
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.11.0 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {'min_num_params': 100000000.0, 'offload_params': True, 'sharding_strategy': 1}
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

My code is in `accelerator.py` [accelerator.zip](https://github.com/huggingface/accelerate/files/8875389/accelerator.zip).

I followed the example in ["Fully Sharded Data Parallel" ](https://huggingface.co/docs/accelerate/fsdp), 
1. I configured accelerate environment by  `accelerate config`
> In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
> Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
> How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
> Do you want to use DeepSpeed? [yes/NO]: NO
> Do you want to use FullyShardedDataParallel? [yes/NO]: yes
> What should be your sharding strategy ([1] FULL_SHARD, [2] SHARD_GRAD_OP)? [1]: 1
> Do you want to offload parameters and gradients to CPU? [yes/NO]: yes
> What should be your FSDP's minimum number of parameters for Default Auto Wrapping Policy? [1e8]: 
> How many GPU(s) should be used for distributed training? [1]:2
> Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: fp16

2. I ran the code with bash ` accelerate launch ./accelerator.py`
It fialed with the error:
> File "/root/anaconda3/envs/XX/lib/python3.8/site-packages/accelerate/utils/dataclasses.py", line 287, in __post_init__
>     from torch.distributed.fsdp.fully_sharded_data_parallel import CPUOffload, ShardingStrategy
> ImportError: cannot import name 'ShardingStrategy' from 'torch.distributed.fsdp.fully_sharded_data_parallel'

The reason is I installed the stable version of [PyTorch 1.11 Release](https://github.com/pytorch/pytorch/blob/bc2c6edaf163b1a1330e37a6e34caf8c553e4755/torch/distributed/fsdp/fully_sharded_data_parallel.py) instead of the latest dev version of [fully_sharded_data_parallel.py](https://github.com/pytorch/pytorch/blob/a2d2981e8e5e128d4e642494bbb5e037ae9933ff/torch/distributed/fsdp/fully_sharded_data_parallel.py#L104), which has no class `ShardingStrategy` in `torch.distributed.fsdp.fully_sharded_data_parallel`

### Expected behavior

```Shell
Could you please possibly fix this by modifying the accelerate framework to work with PyTorch v1.11.0 Release (https://github.com/pytorch/pytorch/releases/tag/v1.11.0).
Thanks a lot.
```

**Comment by pacman100** [comment]
Hello, for FSDP to work properly, many fixes from their 1.12 dev versions are required.
Please refer explanation in #[346](https://github.com/huggingface/accelerate/issues/346#issuecomment-1119510426) for more information.

**Comment by h2bit** [comment]
Understood, thanks for your quick reply!
