### ISSUE TITLE
Error when pickling accelerated optimizers with PyTorch 1.13

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/accelerate#805]
### System Info

```Shell
$ pip list
Package                  Version
------------------------ ----------
accelerate               0.13.2
numpy                    1.23.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                21.3
pip                      22.3
psutil                   5.9.3
pyparsing                3.0.9
PyYAML                   6.0
setuptools               65.5.0
torch                    1.13.0
typing_extensions        4.4.0
wheel                    0.37.1
```

Same issue with torch-cpu.

OS: Ubuntu 20.04

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import pickle
import accelerate
import torch

model = torch.nn.Linear(10, 10)
optimizer = torch.optim.SGD(model.parameters(), 0.1)
pickle.loads(pickle.dumps(optimizer))  # works

accelerator = accelerate.Accelerator(mixed_precision='fp16')
optimizer2 = accelerator.prepare(optimizer)
pickle.loads(pickle.dumps(optimizer2))  # fails
```

### Expected behavior

I ran into a problem with accelerate and PyTorch 1.13. It appears that optimizers cannot be pickled anymore after being accelerated. When running the attached script, I get:

```
Traceback (most recent call last):
  File ".../skorch/foo.py", line 12, in <module>
    pickle.loads(pickle.dumps(optimizer2))
  File ".../torch/optim/optimizer.py", line 84, in __setstate__
    self.defaults.setdefault('differentiable', False)
  File ".../accelerate/optimizer.py", line 90, in defaults
    return self.optimizer.defaults
AttributeError: 'AcceleratedOptimizer' object has no attribute 'optimizer'
```

The offending addition on PyTorch seems to be this line:

https://github.com/pytorch/pytorch/blob/23fe6c8ca15ec2cf6ea74f93aa91cae343ea534f/torch/optim/optimizer.py#L84

which was not present in PyTorch 1.12. At object creation time, PyTorch now tries to access the `defaults` attribute, which in turn calls the `defaults` property in accelerate, which requires the `optimizer` attribute, which doesn't exist and thus errors. At first glance, it looks like `AcceleratedOptimizer` might need its own `__getstate__` and `__setstate__` to solve this but I'm not sure.

**Comment by sgugger** [comment]
Would you have time to look at this @pacman100 ?

**Comment by pacman100** [comment]
Thank you @BenjaminBossan for the detailed report and suggestions. With PyTorch 1.12 also, when I tried to print the loaded optimizer `print(pickle.loads(pickle.dumps(optimizer2)))`, I got the same error 
```
Traceback (most recent call last):
  File "/home/sourab/temp/issue_805.py", line 13, in <module>
    print(pickle.loads(pickle.dumps(optimizer2)))
  File "/home/sourab/miniconda3/envs/ml/lib/python3.10/site-packages/torch/optim/optimizer.py", line 74, in __repr__
    for i, group in enumerate(self.param_groups):
  File "/home/sourab/accelerate/src/accelerate/optimizer.py", line 82, in param_groups
    return self.optimizer.param_groups
AttributeError: 'AcceleratedOptimizer' object has no attribute 'optimizer'
```

Please let us know if the above PR fixes this issue.

**Comment by BenjaminBossan** [comment]
> With PyTorch 1.12 also, when I tried to print the loaded optimizer `print(pickle.loads(pickle.dumps(optimizer2)))`, I got the same error

That's strange, with the exact same environment but replacing `torch==1.13.0` by `torch==1.12.0`, I don't get the error. Also, the CI on skorch, which originally surfaced the issue for me, also works with 1.12. But anyway, it won't hurt even with older versions.

Regarding the PR, a small suggestion would be to return a defensive copy: `self.__dict__.copy()`. It's for the edge case that another caller gets the state and modifies it (e.g. deleting a key), which currently would mutate the original optimizer.
