### PR TITLE
fix: Add `device=torch.get_default_device()` in `torch.Generator`s

### PR DESCRIPTION
**Pull request by saforem2**
# What does this PR do?

Replaces calls to

```python
torch.Generator()
```

with

```python
torch.Generator(device=torch.get_default_device())
```

in [`src/accelerate/data_loader.py`](src/accelerate/data_loader.py).

Prior to this fix, I was seeing:

<details closed><summary>🐛 <b>Bug</b>:</summary>

```python
File /lus/flare/projects/datascience/foremans/projects/argonne-lcf/AuroraGPT/venvs/aurora_nre_models_frameworks-2024.2.1_u1/lib/python3.10/site-packages/accelerate/data_loader.py:99, in SeedableRandomSampler.__iter__(self)
     97 # print("Setting seed at epoch", self.epoch, seed)
     98 self.generator.manual_seed(seed)
---> 99 yield from super().__iter__()
    100 self.set_epoch(self.epoch + 1)

File /opt/aurora/24.180.3/frameworks/aurora_nre_models_frameworks-2024.2.1_u1/lib/python3.10/site-packages/torch/utils/data/sampler.py:167, in RandomSampler.__iter__(self)
    165 else:
    166     for _ in range(self.num_samples // n):
--> 167         yield from torch.randperm(n, generator=generator).tolist()
    168     yield from torch.randperm(n, generator=generator).tolist()[:self.num_samples % n]

File /opt/aurora/24.180.3/frameworks/aurora_nre_models_frameworks-2024.2.1_u1/lib/python3.10/site-packages/torch/utils/_device.py:78, in DeviceContext.__torch_function__(self, func, types, args, kwargs)
     76 if func in _device_constructors() and kwargs.get('device') is None:
     77     kwargs['device'] = self.device
---> 78 return func(*args, **kwargs)

RuntimeError: Expected a 'xpu' device type for generator but found 'cpu'
```

</details>

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr

### CODE REVIEW

**Comment by saforem2** [comment]
awesome, thanks for getting this resolved quickly!! 🙌

**Comment by nordysu** [comment]
This change make accelerate only work on PyTorch>=2.3. 

Is that OK for all?

**Comment by universuen** [comment]
> This change make accelerate only work on PyTorch>=2.3.
> 
> But the install requirements:
> 
> ```
>     install_requires=[
>         "numpy>=1.17,<3.0.0",
>         "packaging>=20.0",
>         "psutil",
>         "pyyaml",
>         "torch>=2.0.0",
>         "huggingface_hub>=0.21.0",
>         "safetensors>=0.4.3",
>     ]
> ```
> 
> Is that OK for all?

Hi @muellerzr, plz kindly check this. When running with torch 2.1, there is an error `AttributeError: module 'torch' has no attribute 'get_default_device' `. I think we may need a more compatible solution for the torch generator's device.
