### PR TITLE
Fix FSDP2 crash with ignored_params on torch < 2.7.0

### LINKED ISSUE #3923: fsdp2 + lora | TypeError: fully_shard() got an unexpected keyword argument 'ignored_params'
I want to use fsdp2 to train Qwen-Image with peft-lora by setting:

command line:
```
accelerate launch \
  --mixed_precision=bf16 \
  --machine_rank=${RANK} \
  --main_process_ip=${MASTER_ADDR} \
  --main_process_port=${MASTER_PORT} \
  --num_machines=${WORLD_SIZE} \
  --num_processes=$((WORLD_SIZE*8)) \
  --use_fsdp \
  train_dreambooth_diffusers.py \
  --config config/train_imagenet.yaml
```

key code pieces:
```
def set_fsdp2_env():
    os.environ["ACCELERATE_USE_FSDP"] = 'true'
    os.environ["FSDP_AUTO_WRAP_POLICY"] = 'TRANSFORMER_BASED_WRAP'
    # os.environ["FSDP_BACKWARD_PREFETCH"] = 'BACKWARD_PRE' # removed for fsdp2
    os.environ["FSDP_TRANSFORMER_CLS_TO_WRAP"] = 'QwenImageTransformerBlock'
    os.environ["FSDP_TRANSFORMER_LAYER_CLS_TO_WRAP"] = 'QwenImageTransformerBlock'
    os.environ["FSDP_CPU_RAM_EFFICIENT_LOADING"] = 'false'
    # os.environ["FSDP_SHARDING_STRATEGY"] = "FULL_SHARD" # only for fsdp1
    os.environ["FSDP_RESHARD_AFTER_FORWARD"] = "true" # only for fsdp2, equal to "FULL_SHARD" in fsdp1
    os.environ["FSDP_STATE_DICT_TYPE"] = "SHARDED_STATE_DICT" # "SHARDED_STATE_DICT" for fsdp2
    # os.environ["FSDP_SYNC_MODULE_STATES"] = "false" # redundant for fsdp2    
    # os.environ["FSDP_USE_ORIG_PARAMS"] = 'true' # removed for fsdp2

def main():
    init_handler = InitProcessGroupKwargs()
    init_handler.timeout = datetime.timedelta(seconds=1800)
    set_fsdp2_env()
    fsdp_plugin = FullyShardedDataParallelPlugin(
        fsdp_version=2, # support partially trainable params, such as lora
    )
    kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
    accelerator = Accelerator(
        gradient_accumulation_steps=config.train.gradient_accumulation_steps,
        mixed_precision=config.train.efficiency.mixed_precision,
        project_config=ProjectConfiguration(project_dir=config.snapshot.output_dir),
        fsdp_plugin=fsdp_plugin,
        kwargs_handlers=[init_handler, kwargs],
        step_scheduler_with_optimizer=False
    )
    transformer = QwenImageTransformer2DModel.from_pretrained(
          config.module.pipeline.path,
          subfolder="transformer",
          # revision=args.revision,
          # variant=args.variant,
          # quantization_config=quantization_config,
          torch_dtype=weight_dtype,
    )
    target_modules = [
            "attn.to_k",
            "attn.to_q",
            "attn.to_v",
            "attn.to_out.0",
            "attn.add_k_proj",
            "attn.add_q_proj",
            "attn.add_v_proj",
            "attn.to_add_out",
            "img_mlp.net.0.proj",
            "img_mlp.net.2",
            "txt_mlp.net.0.proj",
            "txt_mlp.net.2",
     ]
    # now we will add new LoRA weights the transformer layers
    transformer_lora_config = LoraConfig(
        r=config.train.lora_rank,
        lora_alpha=config.train.lora_alpha,
        lora_dropout=0.,
        init_lora_weights="gaussian",
        target_modules=target_modules,
    )
    transformer = get_peft_model(transformer, transformer_lora_config)
    # Prepare everything with our `accelerator`.
    transformer, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
       transformer, optimizer, train_dataloader, lr_scheduler
    )
```

and raised error:
```
File "xxx/lib/python3.10/site-packages/accelerate/accelerator.py", line 1555, in prepare
[rank2]:     result = self._prepare_fsdp2(*args)
[rank2]:   File "xxx/lib/python3.10/site-packages/accelerate/accelerator.py", line 1711, in _prepare_fsdp2
[rank2]:     model = fsdp2_prepare_model(self, model)
[rank2]:   File "xxx/lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 675, in fsdp2_prepare_model
[rank2]:     fully_shard(module, **fsdp2_kwargs)
[rank2]:   File "xxx/lib/python3.10/site-packages/torch/distributed/_composable/contract.py", line 125, in wrapper
[rank2]:     updated = func(inp_module, *args, **kwargs)
[rank2]: TypeError: fully_shard() got an unexpected keyword argument 'ignored_params'
```

How can I set the config for accelerate using fsdp2 to train peft-lora?
Thanks!

pip package version:
torch 2.6.0+cu124
accelearte 1.12.0
peft 0.18.1
diffusers 0.37.0.dev0

### PR DESCRIPTION
**Pull request by Mr-Neutr0n**
## Summary

- Fixes the `TypeError: fully_shard() got an unexpected keyword argument 'ignored_params'` crash when using FSDP2 with LoRA adapters on PyTorch < 2.7.0
- The `ignored_params` kwarg was unconditionally included in `fsdp2_kwargs`, but `torch.distributed.fsdp.fully_shard()` only supports this parameter starting from torch 2.7.0
- Moved `ignored_params` out of the base kwargs dict and only adds it conditionally when `torch >= 2.7.0` and `ignored_modules` is configured

Note: there was already a version guard in `dataclasses.py` that sets `ignored_modules` to `None` for torch < 2.7.0, but `get_parameters_from_modules(None, ...)` returns an empty `set()`, so the key was still present in the kwargs dict and caused the TypeError.

Fixes #3923

## Test plan

- [ ] Verify FSDP2 + LoRA training works on torch 2.6.x without the `TypeError`
- [ ] Verify FSDP2 with `ignored_modules` still works correctly on torch >= 2.7.0
- [ ] Run existing FSDP2 tests to ensure no regressions

### CODE REVIEW

**Comment by Mr-Neutr0n** [comment]
Friendly bump! Let me know if there's anything I should update or improve to help move this forward.
