### PR TITLE
Remove init_hook_kwargs

### PR DESCRIPTION
**Pull request by fxmarty**
Introduced in https://github.com/huggingface/accelerate/pull/2330 but it is quite unnecessary

The test
```
 FAILED tests/test_accelerator.py::AcceleratorTester::test_accelerator_bnb_cpu_error - TypeError: init_hook() got an unexpected keyword argument 'tied_params_map'
```

now passes

### CODE REVIEW

**Comment by muellerzr** [comment]
@fxmarty let's go ahead and rebase please 🙏

**Review by muellerzr — COMMENTED** [review]
Thanks!
