### ISSUE TITLE
TypeError: SageMakerConfig.__init__() missing 1 required positional argument: 'debug'

### ISSUE THREAD

**Issue by mbahri** [huggingface/accelerate#1920]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.19.0-1026-aws-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.13 GB
- GPU type: NVIDIA A10G
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

`accelerate config` fails for SageMaker with `accelerate==0.22.0`

Steps to reproduce the behaviour:
1. `pip install -U 'accelerate[sagemaker']`
2. `accelerate config`
3. I selected options `AWS -> AWS Profile -> Provide IAM Role Name -> No distributed training -> no` and left everything else to the default values
4. Accelerate fails to create and save a `SageMakerConfig` object

### Expected behavior

SageMaker configuration gets created and saved as `~/.cache/huggingface/accelerate/default_config.yaml`

This was working in `accelerate 0.21.0`

**Comment by muellerzr** [comment]
Can you install via `pip install git+https://github.com/huggingface/accelerate`? I believe this was fixed via https://github.com/huggingface/accelerate/pull/1904

**Comment by mbahri** [comment]
It works, thanks and sorry for the duplicate issue!
